version: "3.1"
nlu:
  - intent: greet
    examples: |
      - hello
      - hi
      - good morning

  - intent: feedback
    examples: |
      - I loved the service
      - The room was dirty
      - My AC is not working
